---
title: "scCoAnnotate `r params$cons_type` - `r params$sample`"
output: 
  html_document:
    df_print: paged
    theme: flatly
    toc: yes
    toc_float: yes
    toc_depth: 1 
    code_folding: hide
params: 
    refs: ''
    tools: ''
    consensus: ''
    cons_tools: ''
    output_dir: ''
    sample: ''
    threads: ''
    marker_genes: ''
    query: ''
    cons_type: ''
    ontologies: ''
---

```{r setup, knitr_options, echo=F}
knitr::opts_chunk$set(message = FALSE, warning=FALSE)
```

```{r fig.show='hide', include=F}
library(tidyverse)
library(ComplexHeatmap)
library(Seurat)
library(MetBrewer)
library(plotly)
library(kableExtra)

#empty plotly plot to make sure the other plotly plots get printed later 
plotly_empty() 

# format notebook parameters 
refs = as.character(params$refs)
threads = as.numeric(params$threads)
ontologies = strsplit(params$ontologies, split = ' ')[[1]]
consensus = strsplit(params$consensus, split = ' ')[[1]]
names(consensus) <- str_replace(basename(consensus), "^Prediction_Summary_", "") %>% str_replace("\\.tsv$", "")

tools = strsplit(params$tools, split = ' ')[[1]]
cons_tools = strsplit(params$cons_tools, split = ' ')[[1]]
marker_genes = strsplit(params$marker_genes, split = ' ')[[1]]
cons_type = params$cons_type

if(cons_tools == 'all'){
  cons_tools = c(tools)
}else{
  cons_tools = c(cons_tools)
}
```

```{r}
harmonize_unresolved = function(pred, ref_labels){
  pred %>%
  column_to_rownames('cellname') %>%
  mutate(across(where(is.character), ~ifelse(. %in% c(ref_labels$label, 'No Consensus'), ., 'Unresolved'))) %>%
  return()
}

plot_tool_correlation_heatmap = function(seurat, tools){
 
 mat = query@meta.data %>%
  select(all_of(tools)) %>%
  rownames_to_column('cell') %>%
  pivot_longer(!cell) %>%
  mutate(value = factor(value)) %>%
  mutate(value = as.numeric(value)) %>%
  pivot_wider(names_from = name, values_from = value) %>%
  column_to_rownames('cell') %>%
  cor()

  mat[is.na(mat)] = 0

  col_fun = circlize::colorRamp2(c(-1, 0, 1), c("#2274A5", "beige", "#F75C03"))

 count = query@meta.data %>%
  select(all_of(tools)) %>%
  rownames_to_column('cell') %>%
  pivot_longer(!cell) %>%
  filter(value %in% c('Unresolved', 'No Consensus')) %>%
  dplyr::count(name, .drop = F) %>%
  mutate(freq = round(n/nrow(query@meta.data)*100)) %>%
  select(!n) %>%
  column_to_rownames('name')

  count[setdiff(names(seurat@meta.data %>% select(tools)), rownames(count)),] = 0
  count = count[order(match(rownames(count), colnames(mat))), , drop = FALSE]

  ha = columnAnnotation('% Unresolved/No Consensus' = anno_barplot(count, border = F, gp = gpar(fill = '#596475', col = '#596475')))

  h = ComplexHeatmap::Heatmap(mat,
                        name = 'Correlation',
                        col = col_fun,
                        width = ncol(mat)*unit(7, "mm"),
                        height = nrow(mat)*unit(7, "mm"),
                        rect_gp = gpar(col = "white", lwd = 2), 
                        top_annotation = ha, 
                        show_column_dend = F)
  return(h)
}

create_color_pal = function(class, mb = 'Juarez'){
  pal = sample(met.brewer(mb, length(class)))  
  names(pal) = class
  pal['Unresolved'] = 'lightgrey'
  pal['No Consensus'] = 'grey'
  return(pal)
}

plot_bar_largest_group = function(seurat, meta_column = '', pal = pal, fr = 0.1){
  
df = seurat@meta.data %>%
  count(seurat_clusters, .data[[meta_column]]) %>%
  group_by(seurat_clusters) %>% 
  mutate(`%` = (n / sum(n)))  %>% 
  mutate(meta = ifelse(`%` < fr, NA, .data[[meta_column]]))

pal = pal[unique(na.omit(df$meta))]

df = df %>% 
     mutate(meta = factor(meta, levels = c(NA, names(pal)), exclude = NULL))

p1 = df %>%
  ggplot(aes(x = seurat_clusters, y = `%`, fill = meta, text = sprintf(" %s <br> %s ", 
                                                                       meta, 
                                                                       scales::percent(`%`, scale = 100, accuracy = .1)))) +
  geom_bar(stat = 'identity', position="fill") +
  scale_fill_manual(values = pal, na.value = 'white', name = '') +
  scale_y_continuous(expand = c(0,0), labels = scales::percent_format(scale = 100, accuracy = 1)) +
  coord_flip() +
  theme_bw() +
  theme(text = element_text(size = 10),
        axis.title = element_blank(),
        axis.line = element_line(size = 0.5),
        panel.border = element_blank(),
        panel.grid = element_blank(),
        strip.background = element_blank(), 
        aspect.ratio = 0.5) 

 p2 = ggplotly(p1, tooltip = c('text')) %>% toWebGL()
 
 return(p2)
}

plot_percentage_predicted_consensus_class = function(seurat, tools){
  col_fun = circlize::colorRamp2(c(0, 50, 100), c("#2274A5", "beige", "#F75C03"))

x = seurat@meta.data %>%
  select(c('Consensus', tools)) %>%
  group_by(Consensus) %>% 
  pivot_longer(!c('Consensus')) %>%
  group_by(Consensus, name) %>%
  count(value, .drop = F) %>% 
  mutate(freq = n/sum(n)*100) %>%
  filter(Consensus == value) %>%
  select(name, freq, Consensus) %>%
  pivot_wider(values_from = 'freq', names_from = 'Consensus',values_fill = 0) %>%
  column_to_rownames('name')  

  h = ComplexHeatmap::Heatmap(x,
                        name = '%',
                        col = col_fun,
                        width = ncol(x)*unit(4, "mm"),
                        height = nrow(x)*unit(4, "mm"),
                        rect_gp = gpar(col = "white", lwd = 2), row_names_side = 'left',
                        show_row_dend = F, column_names_gp = gpar(size = 7))
  
  return(h)
}

color_class_seurat = function(seurat, meta_column, pal){
  list = list()
  pal['Unresolved'] = 'red'
  pal['No Consensus'] = 'red'
  Idents(seurat) = meta_column
  class = (table(query@meta.data[[meta_column]]) %>% as.data.frame() %>% filter(Freq > 20))$Var
  
  for(c in class){
    lab =  names(Idents(seurat)[Idents(seurat) == c])
    p = DimPlot(seurat, cells.highlight = lab,  cols = 'lightgrey', cols.highlight = pal[c], pt.size = 1) + umap_theme + ggtitle(c)
    list[[c]] = p 
  }
  
  return(list)
}

feature_plot_seurat = function(seurat, genes){
  list = list()

  genes = genes[genes %in% rownames(seurat@assays$RNA)]
  for(g in genes){
    p = FeaturePlot(seurat, features = g, cols = c("#F2EFC7", "#BC412B"), order = T) + umap_theme + ggtitle(g)
    list[[g]] = p 
  }  
  return(list)
}

feature_plot_seurat_meta = function(seurat, meta_cols){
  list = list()

  meta_cols = meta_cols[meta_cols %in% colnames(seurat@meta.data)]
  for(mc in meta_cols){
    p = FeaturePlot(seurat, features = mc, cols = c("#F2EFC7", "#BC412B"), order = T) + umap_theme + theme(legend.position = 'right') + ggtitle(mc)
    list[[mc]] = p 
  }  
  return(list)
}

umap_plotly = function(seurat, meta_column, pal){

  p1 = cbind(seurat@reductions$umap@cell.embeddings, seurat@meta.data) %>%
  slice(sample(1:n())) %>%
  ggplot(aes(UMAP_1, UMAP_2, color = .data[[meta_column]], text = .data[[meta_column]])) + 
  geom_point(alpha = 0.8) + 
  scale_color_manual(values = pal) +
  theme_bw() + umap_theme + theme(legend.position = 'right') 

  p2 = ggplotly(plot = p1, tooltip = c('text')) %>% layout(autosize = F, width = 550, height = 450) %>% toWebGL()

  return(p2)
}

calculate_percentage_unresolved = function(pred, order, cons_tools){
  warn = pred %>% 
    select(order) %>%
    pivot_longer(order) %>% 
    mutate(value = factor(value)) %>%
    group_by(name) %>%
    count(value, .drop = F) %>%
    mutate(frac = n/sum(n)*100) %>%
    filter(!(!name == 'Consensus' & value == 'No Consensus')) %>%
    filter(value %in% c('No Consensus', 'Unresolved')) %>%
    mutate(in_cons = ifelse(name %in% cons_tools & name != 'Consensus', 'YES', '')) %>%
    mutate(warn = case_when(frac >= 70 ~ 'HIGH', 
                            frac < 70 & frac > 30 ~ 'MEDIUM',
                            frac <= 30 ~ 'LOW'))
   if(nrow(warn) != 0){
   warn = data.frame(TOOL = warn$name, 
                     'IN CONSENSUS' = warn$in_cons,
                     LABEL = warn$value, 
                     PERCENTAGE = warn$frac, 
                     FLAG = warn$warn) %>%
          mutate(TOOL = factor(TOOL, levels = order)) 

   warn = warn[order(warn$TOOL),]

   warn$FLAG = cell_spec(warn$FLAG, 
                         bold = T,
                         background = case_when(warn$FLAG == 'HIGH' ~ "red",
                                                warn$FLAG == 'MEDIUM' ~ "yellow",
                                                warn$FLAG == 'LOW' ~ "green"))
   
   warn$TOOL = cell_spec(warn$TOOL,
                         bold = ifelse(warn$TOOL == 'Consensus', T, F),
                         background = ifelse(warn$TOOL == 'Consensus', 'black', 'white'),
                         color = ifelse(warn$TOOL == 'Consensus', 'white', 'black'))
   }
   
   return(warn)
}

umap_theme = theme(aspect.ratio = 1,
        text = element_text(size = 10), 
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank(), 
        panel.border = element_rect(colour = "grey", fill=NA, size=0.5),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "none")
```


```{r}
# read prediction summary for each reference 
list = list()

for(ont in ontologies){
  list[[ont]]$lab = data.table::fread(paste0(params$output_dir, '/model/', refs, '/ontology/labels_',ont,'.csv'), header = T, fill = T) %>% as.data.frame()
 
  list[[ont]]$pred = data.table::fread(consensus[ont]) %>% 
                       harmonize_unresolved(., list[[ont]]$lab) 

  # create reference pal
  list[[ont]]$pal = create_color_pal(list[[ont]]$lab$label)

}

# read expression matrix for sample  
query = data.table::fread(paste0(params$query), 
                                 nThread=threads, 
                                 header=T, 
                                 data.table=F) %>%
        column_to_rownames('V1') 
```

```{r, results='hide'}
# create seurat object from expression matrix 
set.seed(12345)
query = t(query)
query = CreateSeuratObject(query, row.names = colnames(query))

query = query %>% 
  NormalizeData() %>% 
  FindVariableFeatures() %>% 
  ScaleData() %>% 
  RunPCA() %>% 
  FindNeighbors(dims = 1:30) %>%
  FindClusters(resolution = 0.5) %>%
  RunUMAP(dims = 1:30)

#create cluster pal 
cluster_pal = create_color_pal(query$seurat_clusters)
```

```{r fig.width=8,fig.height=8,echo=FALSE,message=FALSE,results="asis"}
set.seed(12345)
cat("\n")

cat("  \n# Sample \n")
  
  cat("<h3>Clusters</h3>")
  cat("\n")
  
  p = umap_plotly(query, 'seurat_clusters', cluster_pal)
  print(htmltools::tagList(p))
  
  cat("<h3>Expression selected genes</h3>")
  cat("\n")
  
  if(!length(marker_genes) == 0){
    l = feature_plot_seurat(query, marker_genes)
    if(length(marker_genes) < 9){
      cowplot::plot_grid(plotlist = l[1:9], ncol = 3) %>% print()
    }else{
      for(i in seq(from = 1, by = 9, length.out = round(length(marker_genes)/9))){
      cowplot::plot_grid(plotlist = l[i:(i+8)], ncol = 3) %>% print()
     }
    }
  }

cat("\n")

for(ont in ontologies){
  
  query = AddMetaData(query, list[[ont]]$pred)
  
  cat("  \n#",  ont, "{.tabset} \n")
  
  cat("\n")
  
  cat("  \n## Prediction QC \n")
  
  cat("<h3>Percentage Unresolved</h3>")
  cat("\n")
  tool_list <- c(grep(pattern = "^Consensus_",x = colnames(list[[ont]]$pred),value = T),tools)
  cons_tool_list <- c(grep(pattern = "^Consensus_",x = colnames(list[[ont]]$pred),value = T),cons_tools)
  calculate_percentage_unresolved(list[[ont]]$pred, order = tool_list, cons_tools = cons_tool_list) %>% 
  kbl(escape = FALSE, row.names = F) %>% 
  kable_styling(position = "center") %>%
  print()
  
  cat("<h3>Correlation between tools</h3>")
  cat("\n")

  h = plot_tool_correlation_heatmap(query, tools = tool_list)
  draw(h)
  
  cat("<h3>Percentage overlap between tools and consensus</h3>")  
  cat("\n")
  
  cat("\n")
  cat("  \n## Prediction {.tabset} \n")
  for(t in tool_list){
    cat("  \n### ", t , " \n")
    

    cat("<h3>Top class per cluster</h3>")
    cat("\n")

    p = plot_bar_largest_group(query, t, fr = 0.1, pal = list[[ont]]$pal)
    print(htmltools::tagList(p))
    
    cat("<h3>UMAP</h3>")
    cat("\n")

    p = umap_plotly(query, t, list[[ont]]$pal)
    print(htmltools::tagList(p))
  
    if(grepl(pattern = "^Consensus_CAWPE_",x = t)){
      
        cat("<h3>CAWPE Score</h3>")
        cat("\n")

        l = feature_plot_seurat_meta(query, gsub(pattern = "^Consensus",replacement = "CAWPE",x = t))
        cowplot::plot_grid(plotlist = l, ncol = 2) %>% print()
    }

    cat("<h3>UMAP per class</h3>")
    cat("\n")
    
    l = color_class_seurat(query, t, list[[ont]]$pal)
    if(length(l)< 9){
      cowplot::plot_grid(plotlist = l[1:9], ncol = 3) %>% print()
    }else{
      for(i in seq(from = 1, by = 9, length.out = round(length(l)/9))){
      cowplot::plot_grid(plotlist = l[i:(i+8)], ncol = 3) %>% print()
      }
    }
  
    cat("\n")
  }
}
```

# Report Info 

## Parameters 

```{r echo=FALSE,message=FALSE,results="asis"}
for(p in names(params)){
  cat(" \n -",p,": ", params[[p]], " \n")
}
```

## Session  

```{r}
sessionInfo()
```
